CREATE TABLE [dbo].[User]
(
	[Id] CHAR(32) NOT NULL PRIMARY KEY,
	[Email] NVARCHAR(255) NOT NULL UNIQUE,
	[Secret] NVARCHAR(255) NULL,
	[Salt] NVARCHAR(255) NULL,
	[CreateDateTime] DATETIME NOT NULL,
	[UpdateDateTime] DATETIME, 
    [Role] INT NOT NULL DEFAULT 0,
)
